// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJN60GwCPcPFtIlOk1nSVN-me5r8PGYTg',
    appId: '1:217328360375:android:d74c88ebfc999b22892632',
    messagingSenderId: '217328360375',
    projectId: 'favorite-location-8ea47',
    databaseURL: 'https://favorite-location-8ea47-default-rtdb.firebaseio.com',
    storageBucket: 'favorite-location-8ea47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9uez1UQtuEU8BCdQos3y4QxyEnpOzNbU',
    appId: '1:217328360375:ios:b5518a876bbae9e5892632',
    messagingSenderId: '217328360375',
    projectId: 'favorite-location-8ea47',
    databaseURL: 'https://favorite-location-8ea47-default-rtdb.firebaseio.com',
    storageBucket: 'favorite-location-8ea47.appspot.com',
    iosClientId: '217328360375-4oljr0sifam3v56e0h3ags40pmirr2p0.apps.googleusercontent.com',
    iosBundleId: 'com.example.favoritePlaces',
  );
}
